export const ascii = [
    {char: " ", byte: 0xFF},
    {char: "0", byte: 0xD9},
    {char: "1", byte: 0xDA},
    {char: "2", byte: 0xDB},
    {char: "3", byte: 0xDC},
    {char: "4", byte: 0xDD},
    {char: "5", byte: 0xDE},
    {char: "6", byte: 0xDF},
    {char: "7", byte: 0xE0},
    {char: "8", byte: 0xE1},
    {char: "9", byte: 0xE2},
    {char: "A", byte: 0x35},
    {char: "B", byte: 0x36},
    {char: "C", byte: 0x37},
    {char: "D", byte: 0x38},
    {char: "E", byte: 0x39},
    {char: "F", byte: 0x3A},
    {char: "G", byte: 0x3B},
    {char: "H", byte: 0x3C},
    {char: "I", byte: 0x3D},
    {char: "J", byte: 0x3E},
    {char: "K", byte: 0x3F},
    {char: "L", byte: 0x40},
    {char: "M", byte: 0x41},
    {char: "N", byte: 0x42},
    {char: "O", byte: 0x43},
    {char: "P", byte: 0x44},
    {char: "Q", byte: 0x45},
    {char: "R", byte: 0x46},
    {char: "S", byte: 0x47},
    {char: "T", byte: 0x48},
    {char: "U", byte: 0x49},
    {char: "V", byte: 0x4A},
    {char: "W", byte: 0x4B},
    {char: "X", byte: 0x4C},
    {char: "Y", byte: 0x4D},
    {char: "Z", byte: 0x4E},
    {char: "a", byte: 0x65},
    {char: "b", byte: 0x66},
    {char: "c", byte: 0x67},
    {char: "d", byte: 0x68},
    {char: "e", byte: 0x69},
    {char: "f", byte: 0x6A},
    {char: "g", byte: 0x6B},
    {char: "h", byte: 0x6C},
    {char: "i", byte: 0x6D},
    {char: "j", byte: 0x6E},
    {char: "k", byte: 0x6F},
    {char: "l", byte: 0x70},
    {char: "m", byte: 0x71},
    {char: "n", byte: 0x72},
    {char: "o", byte: 0x73},
    {char: "p", byte: 0x74},
    {char: "q", byte: 0x75},
    {char: "r", byte: 0x76},
    {char: "s", byte: 0x77},
    {char: "t", byte: 0x78},
    {char: "u", byte: 0x79},
    {char: "v", byte: 0x7A},
    {char: "w", byte: 0x7B},
    {char: "x", byte: 0x7C},
    {char: "y", byte: 0x7D},
    {char: "z", byte: 0x7E}
];

export const sentences = {
    "quotes": [
        {line1: "  BUT OUR PRINCESS  ", line2: "IS IN ANOTHER CASTLE"},
        {line1: "   OH DAISY DAISY   ", line2: "  THANK YOU MARIO   "},
        {line1: "  MARIOS ADVENTURE  ", line2: "    IS NOW OVER     "},
        {line1: "   YOU REALLY BEAT  ", line2: " ME THIS TIME MARIO "}
    ],
    "facts": [
        {line1: "   A SUPERJUMP IS   ", line2: "  HOLDING JUMP FOR  ", line3: "  21 TO 26 FRAMES   "},
        {line1: "   WHEN YOU KILL    ", line2: "  100 ENEMIES YOU   ", line3: "   GET A STARMAN    "},
        {line1: "  WHEN YOU GET HIT  ", line2: " YOU HAVE 126 FRAMES", line3: "  OF INVINCIBILITY  "},
        {line1: "  IT IS FASTER TO   ", line2: "  NOT JUMP AROUND   ", line3: " WITH MOON PHYSICS  "},
        {line1: "     HOLDING UP     ", line2: "   WHILE JUMPING    ", line3: " MAKES YOU GO HIGHER"},
        {line1: "   LET GO OF RUN    ", line2: "    TO DROP OFF     ", line3: "   LEDGES QUICKER   "},
        {line1: " LEAVE WARIO ROOM 1 ", line2: " AT XX0 XX4 OR XX8  ", line3: " TO SPEED UP PHASE 2"},
        {line1: " AFTER HIS PHASE 3  ", line2: " STAND INSIDE WARIO ", line3: " FOR THE SHOE GLITCH"},
        {line1: "    THERE ARE 27    ", line2: "   DISTINCT JUMP    ", line3: "   HEIGHTS IN SML2  "},
        {line1: "  TOTAKAS SONG IS   ", line2: "  HIDDEN SOMEWHERE  ", line3: "  IN MARIO LAND 2   "},
        {line1: "  LOSING ALL YOUR   ", line2: " LIVES MEANS LOSING ", line3: "  ALL GOLDEN COINS  "}
    ],
    "songs": [
        {line1: "   1   2    3   4   ", line2: "    LETS CHA CHA    ",
         line3: "  TAKE UR LEFT FOOT ", line4: "  DIP IT LIKE THIS  ",
         line5: "   PUT YOUR HANDS   ", line6: " RIGHT UP ON UR HIPS",
         line7: "   NOW DO THE DIP   ", line8: "    CHA CHA CHA     "},
        {line1: "      ITS THE       ", line2: "     STAR SONG      ",
         line3: "     THAT FUNKY     ", line4: "     STAR SONG      ",
         line5: "      ITS THE       ", line6: "     STAR SONG      ",
         line7: "     THAT FUNKY     ", line8: "     STAR SONG      "},
        {line1: "  TAKE YOU TO THE   ", line2: "    LAKESIDE INN    ",
         line3: "   PUPPY CHUCKED    ", line4: "    IN THE LAKE     ",
         line5: " THROWING YOUR DOG  ", line6: " RIGHT INTO THE LAKE",
         line7: "   BUT ITS ALRIGHT  ", line8: " HE WILL BE ALRIGHT "},
        {line1: " JUMPING EVERY DAY  ", line2: " JUMPING EVERY DAY  ",
         line3: "   IN THE GARDEN    ", line4: "     AT THE BAY     ",
         line5: "  TAKING YOUR WORD  ", line6: " SO WHAT DO YOU SAY ",
         line7: " JUMPING EVERY DAY  ", line8: " JUMPING EVERY DAY  "},
        {line1: "     A   B   C      ", line2: "   A B C D E F G    ",
         line3: "   H  I  J  K  L    ", line4: "     M  N  O  P     ",
         line5: "     Q   R   S      ", line6: "     T   U   V      ",
         line7: "                    ", line8: "                    "},
        {line1: " I WANT TO THANK YOU", line2: "  ALL FOR WATCHING  ",
         line3: "  HAVE A GOOD DAY   ", line4: "     COME AGAIN     ",
         line5: " THANK YOU SO MUCH  ", line6: " THANK YOU SO MUCH  ",
         line7: " AND UNTIL NEXT TIME", line8: "      GOOD BYE      "}
    ],
    "other": [
        {line: "  SML2 RANDO STAFF  ", offset: 0x6974D},
        {line: "      CREATOR       ", offset: 0x69763},
        {line: "     SLASHINFTY     ", offset: 0x69778},
        {line: "     ROMHACKER      ", offset: 0x6978D},
        {line: "       TORUZZ       ", offset: 0x697A2},
        {line: "     ROMHACKER      ", offset: 0x697B7},
        {line: "    LIGHTBULBSUN    ", offset: 0x697CC},
        {line: "     ROMHACKER      ", offset: 0x697E1},
        {line: "    RACCOON SAM     ", offset: 0x697F6},
        {line: "     ROMHACKER      ", offset: 0x6980B},
        {line: "     SMELLYMOO      ", offset: 0x69820},
        {line: "     PROGRAMMER     ", offset: 0x69835},
        {line: "       VEEARR       ", offset: 0x6984A},
        {line: "  TESTING  PLAYERS  ", offset: 0x698AF},
        {line: "      OH DEER       ", offset: 0x698C4},
        {line: "    BEASTFRISIAN    ", offset: 0x698D9},
        {line: "       TYPWO        ", offset: 0x698EE},
        {line: "      RAVETUBA      ", offset: 0x69903},
        {line: "      WOLFRUNE      ", offset: 0x69918},
        {line: "   I PLAYED THIS    ", offset: 0x6997D},
        {line: "   GAME AS A KID    ", offset: 0x69992},
        {line: " THANK YOU EVERYONE ", offset: 0x699F7},
        {line: "WHO MADE THIS HAPPEN", offset: 0x69A0C},
        {line: "   MY FRIENDS AND   ", offset: 0x69A21},
        {line: "      MY FAMILY     ", offset: 0x69A36},
        {line: "  SPEEDRUNNERS AND  ", offset: 0x69A4B},
        {line: "  RANDO COMMUNITY   ", offset: 0x69A60},
        {line: " NOW FOR SOME FACTS ", offset: 0x69AC6},
        {line: "   THATS ALL FOR    ", offset: 0x69B93},
        {line: "  THIS SEEDS FACTS  ", offset: 0x69BA8},
        {line: "      TIME FOR      ", offset: 0x69C0E},
        {line: "    ICEPLUG SINGS   ", offset: 0x69C22}
    ]
};